[package]
name = "wot-replays"
version = "0.1.0"
authors = ["Sergey Tsaplin <me@sergeytsaplin.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
